name: Run tests

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python_version: ['3.10']
        euphonic_version: ['']
        # Test lowest supported Python/Euphonic versions
        include:
          - os: ubuntu-latest
            python_version: '3.7'
            euphonic_version: '--version 0.6.0'
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Update pip
        shell: bash -l {0}
        run: python -m pip install --upgrade pip
      - name: Install basic Euphonic and dependencies and run tests
        shell: bash -l {0}
        run: |
          python apply_requirements.py ${{ matrix.euphonic_version }}
          python run_tests.py -m "not phonopy_reader" --coverage "coverage.xml"
      - name: Install Euphonic with phonopy_reader extra and run tests
        shell: bash -l {0}
        run: |
          python apply_requirements.py --extras phonopy_reader ${{ matrix.euphonic_version }}
          python run_tests.py -m "phonopy_reader" --coverage "coverage_phonopy_reader.xml"
      - uses: codecov/codecov-action@v3
        if: startsWith(matrix.os, 'ubuntu')
        with:
          files: |
            coverage.xml
            coverage_phonopy_reader.xml
