name: Run tests

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        python: [3.6]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Update pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python apply_requirements.py
      - name: Test with coverage
        run: python run_tests.py --coverage
      - uses: codecov/codecov-action@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          files: coverage.xml
