name: Run tests

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        python: [3.6]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install basic Euphonic and dependencies and run tests
        run: |
          python apply_requirements.py
          python run_tests.py -m "not phonopy_reader" --coverage "coverage.xml"
      - name: Install Euphonic with phonopy_reader extra and run tests
        run: |
          python apply_requirements.py --extras phonopy_reader
          python run_tests.py -m "phonopy_reader" --coverage "coverage_phonopy_reader.xml"
      - uses: codecov/codecov-action@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          files: |
            coverage.xml
            coverage_phonopy_reader.xml
